### ISSUE TITLE
[Crash] Sodium 0.5.8 support

### ISSUE THREAD

**Issue by Anonyku05** [DaFuqs/FluidVoidFading#11] opened 2024-05-06 00:22 UTC
My game crash when entering the End with water going to the void, i saw that this issue is common with these mods, i'm using 1.20.4 Fabric with 0.5.8 Sodium

**Comment by DaFuqs** [comment] 2024-05-06 09:25
I swear, if Sodium did another breaking change I will puke
I will look into it, thank you!

Can you attach your crash log, please?

**Comment by Anonyku05** [comment] 2024-05-06 12:46
There you go:
[crash-2024-05-05_17.47.11-client.txt](https://github.com/DaFuqs/FluidVoidFading/files/15220727/crash-2024-05-05_17.47.11-client.txt)

**Comment by DaFuqs** [comment] 2024-05-06 18:55
[Let me know, if this version works](https://www.dropbox.com/scl/fi/ga8v6f687rp3fmnopf9s1/fluidvoidfading-1.1.5-1.20.4.jar?rlkey=djt7fgsg91j12sst2dooqgbbh&dl=0)

I tried it on MC 1.20.4 with Sodium 0.5.8 and the water rendered nicely without crashes in the end.
If it works for you I will put it on Curseforge and Modrinth

**Comment by Anonyku05** [comment] 2024-05-06 19:42
It's not crashing anymore, but i don't know if it renders correctly or if it is just me:
![image](https://github.com/DaFuqs/FluidVoidFading/assets/48128391/84f88544-d751-4ab6-a5c6-0f8d275a004a)
![image](https://github.com/DaFuqs/FluidVoidFading/assets/48128391/cd22a2db-d807-40ae-8db8-fe8b11b0310e)
![image](https://github.com/DaFuqs/FluidVoidFading/assets/48128391/98b4357f-03ab-4122-8f7b-ba79c84151cf)
![image](https://github.com/DaFuqs/FluidVoidFading/assets/48128391/9e47ed56-546b-41d2-98c9-1af57e2ec4fc)

**Comment by DaFuqs** [comment] 2024-05-07 05:44
Hu. I got nothing. It looks good just using the FluidVoidFading I linked and Sodium 0.5.8:

![image](https://github.com/DaFuqs/FluidVoidFading/assets/26429514/2c6907b4-1397-4df1-8414-f9869f35edcb)

Can you try around if there is another mod in your instance that causes this, please?

**Comment by Anonyku05** [comment] 2024-05-07 16:16
I'm gonna try but it will take a lot of time cuz i have over 200 mods :/

**Comment by DaFuqs** [comment] 2024-05-08 16:10
Good chances it is a mod that tinkers with rendering (shader maybe?), so there should not be too many.

For starters just disable half of the mods, if the issue persists it has to be a mod in that set, if the issue went away, it has to be one of the mods you just disabled. By going 50:50 every step, drilling it down to a single mod should be fairly quick.

**Comment by ThePiekar** [comment] 2024-06-06 00:02
Any updates on this? I'm having a very similar issue (although i have slightly modified one of the mixins in order to have it run with embeddium on forge, so it wouldn't feel exactly fair to post it as an issue) and for the life of me i cannot figure out what causes this.

Also please, take the amount of questionable effort i took to achieve this as a compliment, this mod is really nice.

**Comment by DaFuqs** [comment] 2024-06-19 19:24
So it seems the wack fluid renderer is caused by Sodium/Embeddium's fluid rendering implementation. (hence why it is also showing above the void)
That one has to be fixed on their side, sorry.

**Closed as completed by DaFuqs** 2024-06-19 19:24 UTC

**Comment by ThePiekar** [comment] 2024-06-19 19:31
Through connector, with the newest embeddium version (it now includes a fabric rendering api implementation) it looks about right now.

**Comment by Anonyku05** [comment] 2024-06-19 21:20
> Through connector, with the newest embeddium version (it now includes a fabric rendering api implementation) it looks about right now.

Is the fix working with 1.20.4 ? I mean there haven't been any embeddium update since 2 months

**Comment by ThePiekar** [comment] 2024-06-20 02:04
> Is the fix working with 1.20.4 ? I mean there haven't been any embeddium update since 2 months

Oh sorry, it appears they updated it for 1.20.1 and 1.20.6 but not for 1.20.4.
Quite unfortunate, 1.20.4 seems to be abandoned.
The embeddium version in question is 0.3.20 (released jun 8), it fixed my issue completely.

**Comment by Anonyku05** [comment] 2024-06-21 16:13
Just realized that i don't have embeddium, only lithium and sodium

**Comment by ThePiekar** [comment] 2024-06-21 16:37
> Just realized that i don't have embeddium, only lithium and sodium

I'm aware, sorry for assuming it was obvious, but embeddium is a fork of sodium, meaning they're very similar. That's why I recommended newest embeddium update (which now is moot since it hasn't been updated for your particular version), since it is basically sodium + one major optimalization I believe + a fix for the issue.

In short it is definitely a sodium (so by extension an embeddium) issue, fixed in latest embeddium. If it's possible for you I'd recommend jumping over to a more supported minecraft version.

I have looked through the code myself a bit, and couldn't come up with a satisfactory fix.
